# This rule is not used by the project pg2iceberg-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the replication.pg2iceberg.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pg2iceberg-operator
    app.kubernetes.io/managed-by: kustomize
  name: pg2iceberg-editor-role
rules:
- apiGroups:
  - replication.pg2iceberg.io
  resources:
  - pg2icebergs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.pg2iceberg.io
  resources:
  - pg2icebergs/status
  verbs:
  - get
